package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, FOLLOW, PENDING, ACCEPT, UPLOAD, VISIBILITY, LIST_FILES, REMOVE_FILES, LIST_FILES_RESPONSE, STOP, UPLOAD_RESPONSE, LEAVE, REMOVE_FILE_RESPONSE
}
